-- DESBLOQUEO TOTAL DE LA TABLA DE PERSONAL
ALTER TABLE staff DISABLE ROW LEVEL SECURITY;

-- ASEGURAR QUE EXISTAN LAS COLUMNAS NECESARIAS
DO $$ 
BEGIN 
    BEGIN
        ALTER TABLE staff ADD COLUMN IF NOT EXISTS full_name TEXT;
        ALTER TABLE staff ADD COLUMN IF NOT EXISTS role TEXT;
        ALTER TABLE staff ADD COLUMN IF NOT EXISTS phone TEXT;
        ALTER TABLE staff ADD COLUMN IF NOT EXISTS sex TEXT;
    EXCEPTION WHEN OTHERS THEN 
        RAISE NOTICE 'Columnas ya existen';
    END;
END $$;
